version: "3"

tasks:
  run-enter:
    cmds:
      - go run -v ./... --mode enter
  run-exit:
    cmds:
      - go run -v ./... --mode exit
  build:
    cmds:
      - go build -o bin -v ./...
  test:
    cmds:
      - go test -v ./...
  clean:
    cmds:
      - rm -rf bin/*
      - rm -rf data/*
  decode-data:
    cmds:
      - ~/go/bin/protoscope data $1 > $1.txt
